config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts do
    resources :comments
    #resources :votes, only: [:create, :show, :update, :destroy]
    post '/votes/up' => 'votes#up'
    post '/votes/down' => 'votes#down'
    #delete '/posts/:post_id/votes/clear' => 'votes#vote_clear'
  end
resources :tags
resources :users
resources :topics

get 'signup', to: 'users#new', as: 'signup'
get 'login', to:'session#new', as: 'login'
post 'login', to: 'session#create', as: 'sessions'
post 'logout', to: 'session#destroy', as: 'logout'
end

app/models/post.rb
class Post < ApplicationRecord
require 'obscenity/active_model'

  belongs_to :user
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  # validates :url, url: { allow_blank: true }
  validates :title,  obscenity: { sanitize: true, replacement: "@!#%"}
  validates :content,  obscenity: { sanitize: true, replacement: "@!#%"}

  def self.search(search)
    p = Post.all
    a = []
    p.each do |post|
      post.tags.each do |tag|
        if tag.name.downcase == search.downcase
          a << post
        end
      end
    end
    a
  end

  def score
    self.votes.sum(:value)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :get_post, only:[:show, :edit, :update, :destroy]
  #before_action :require_login
  #skip_before_action :require_login, only:[:new, :create]
  before_action :authorized?, only: [:create, :update, :destroy]

  def index
    # @posts = Post.where(["tags like ?","%#{params[:search]}%"])
    if params[:search]
      @posts = Post.search(params[:search])
    else
      @posts = Post.all.order(id: :desc)
      @posts
    end
  end

  def show
    #list all the comments
    @comments = @post.comments
    #this is for the commenting to get a random user, until we have auth
    @user_sample = User.all.sample
  end

  def new
    @post = Post.new
    #@users = User.all #i dont think we need this -mm
    @topics = Topic.all
  end

  def create
    @post = Post.create(post_params)
    if @post.valid?
      if working_url?(@post.url)
        add_scraped_tags
        get_image
        get_title
      end
      flash[:success] = "you created a post!"
      redirect_to @post
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def edit
    @topics = Topic.all
    @users = User.all
  end

  def update
    @post.update(post_params)
    if @post.valid?
        if working_url?(@post.url)
          @post.tags.destroy_all
          add_scraped_tags
          get_image
          get_title
        end
      redirect_to @post
      flash[:success] = "you edited a post!"
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to edit_post_path
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def add_scraped_tags
    tag_results = get_tags_name["keywords"]
    if tag_results != nil
      tags = tag_results[0].split(", ")
      tags.each do |tag|
        @tags = Tag.find_or_create_by(name: tag)
        @post.tags << @tags
      end
    end
  end

  def working_url?(url)
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
    rescue URI::InvalidURIError
    false
  end

  def get_title
    page = Nokogiri::HTML(open(@post.url))
    web_title = []
    web_title << page.css('title')[0].text
    title = web_title
    if title.first != nil
      @post.link_title = title.first
      @post.save
    end
  end

  def get_image
    page = MetaInspector.new(@post.url)
    image = page.images.best
    if image != nil
      @post.image_url = image
      @post.save
    end
  end

  def get_tags_name
    page = MetaInspector.new(@post.url)
    page.meta_tags['name']
  end

  def post_params
    # params.require(:post).permit(:title, :user_id, :url, :content, :search, :tags, :topic_id) - removing the :tags, and :search -mm
    params.require(:post).permit(:title, :user_id, :url, :content, :topic_id)
  end

  def get_post
    @post = Post.find(params[:id])
  end

  # def require_login
  #   return head(:forbidden) unless session.include? :user_id
  # end

end

app/views/posts/_form.html.erb
<div class="flex-container clearfix">

  <% if logged_in? %>

    <div class="post-form">
      <% if flash[:errors] %>
      <h2>Errors: </h2>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_for @post do |f| %>
        <%= f.label "Title (Required)" %><br>
        <%= f.text_field :title %><br>
        <br>
        <%= f.label "URL (Optional)" %><br>
        <%= f.text_field :url %><br>
        <br>
        <%= f.label "Description (Optional)" %><br>
        <%= f.text_area :content %><br>

        <%= f.label "Topic (Required)" %><br>
        <%= f.collection_select :topic_id, @topics, :id, :name %>
        <br><br>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit %>
      <% end %>
    </div>

  <% else %>
    <div class="empty_posts">Please <%= link_to "login", login_path %> first.</div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class='jumbotron text-left clearfix'>
  <h1>Edit Post</h1>
  <div class="search-box">
  </div>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class='jumbotron text-left clearfix'>
  <h1>All Posts</h1>
  <%= button_tag(type: 'submit', class: "btn btn-light") do %>
    <i class="icon-ok icon-white"><%= link_to "Create Post", new_post_path %></i>
  <% end %>
  <div class="search-box">
    <%= form_tag posts_path, method: "get" do %>
      <%= text_field_tag :search, params[:search], placeholder: "e.g. sports" %>
      <%= submit_tag "Filter Posts" %>
    <% end %>
  </div>
</div>

<%= render '/forms/posts' %>

app/views/posts/new.html.erb
<div class='jumbotron text-left clearfix'>
  <h1>Create A Post</h1>
  <div class="search-box">
  </div>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='jumbotron text-left clearfix'>
  <h1><%=@post.topic.name%> – <%= @post.title %></h1><br><br>
  <%=@post.content%> - <%= link_to @post.user.username, @post.user %>
  <div class="search-box">
    <%= button_tag(type: 'submit', class: "btn btn-light") do %>
      <i class="icon-ok icon-white"><%= link_to "Edit Post", edit_post_path(@post) %></i>
    <% end %>
  </div>
</div>

<div class="post-shell">
  <% if @post.url %>
    <div class="post-header clearfix">
      <div class="post-header-left">
        <img border="0" src="<%= @post.image_url %>" style="max-height: 500px; max-width: 500px;">
      </div>
      <div class="post-header-right">
        <h2><%= link_to @post.link_title, @post.url %></h2>
      </div>
    </div>
  Tags: <% @post.tags.each do |t| %> <%= link_to t.name, t %> <% end %>
  <% end %>

  <br>
  <br>

  <% if @comments.any? %>
  <h4>Comments:</h4>
    <ul>
    <% @comments.each do |c| %>
      <li>"<%= c.content %>" by <%= c.user.username %> | <%= link_to "delete", post_comment_path(c), method: 'delete' %></li>
    <% end %>
    </ul>
  <% end %>

  <div class='jumbotron'>
   <p>Add a comment:</p>
    <% if logged_in? %>
      <%= form_tag("/posts/#{@post.id}/comments", method: 'POST') do %>
        <%= text_field_tag :content %>
        <%= hidden_field_tag :post_id, @post.id %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <!--- in order to create clickable buttons --->
        <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
          <i class="icon-ok icon-white"></i> Comment
        <% end %>
      <% end %>
    <% else %>
      <div>Please <%= link_to "login", login_path %> first.</div>
    <% end %>
  </div>

</div>