config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts do
    resources :comments
    #resources :votes, only: [:create, :show, :update, :destroy]
    post '/votes/up' => 'votes#up'
    post '/votes/down' => 'votes#down'
    #delete '/posts/:post_id/votes/clear' => 'votes#vote_clear'
  end
resources :tags
resources :users
resources :topics

get 'signup', to: 'users#new', as: 'signup'
get 'login', to:'session#new', as: 'login'
post 'login', to: 'session#create', as: 'sessions'
post 'logout', to: 'session#destroy', as: 'logout'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Wroteit</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md bg-dark navbar-dark orangish-nav">
      <a class="navbar-brand" href="<%=posts_path%>"><%= image_tag "wroteit.png", id: "logo-image" %></a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%=users_path%>">Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=posts_path%>">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=topics_path%>">Topics</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=tags_path%>">Tags</a>
          </li>
        </ul>
        <span class="navbar-text text-right">
          <% if logged_in? %>
          Signed in as <%= link_to current_user.username, current_user %> | <%= link_to "Logout", logout_path, method: "post" %>
          <% else %>
          <%= link_to 'Sign Up', '/signup' %>
          <% end %>
        </span>
      </nav>

    <%= yield %>
    <div class="footer-copyright py-3 text-center dark-footer">
          ...and now you <a href="http://www.reddit.com">Reddit</a>
      </div>
  </body>
</html>